(setq inhibit-startup-screen t)
(tool-bar-mode -1)
(scroll-bar-mode -1)
(global-display-line-numbers-mode 1)
(blink-cursor-mode 0)
(setq-default cursor-type `hbar)
(setq-default indent-tabs-mode nil)
(setq-default tab-width 4)
(setq c-basic-offset 4)
(setq c-basic-indent 4)
(add-to-list 'auto-mode-alist '("\\.h\\'" . c++-mode))
